options = odeset('AbsTol',1e-9);
X10 = 1;
X20 = 1;
[t, y] = ode45(@GTAderivs, [0, 5000], [X10, X20], options);
plot(t,y(:,1),'-o',t,y(:,2),'-o');
xlabel('Time t');
ylabel('Population size');
legend('X+(GTA positive)','X-(GTA negative)');
dlmwrite('/Users/Xin/Desktop/projects/GTA_project/output/20160627/matlabout.txt', y(657, 1:end));
dlmwrite('/isi/olga/xin/GTA_project/output/20160627/GTAoutput.txt', [t, y]);